Update combine-json-files.yml

diff --git a/.github/workflows/combine-json-files.yml b/.github/workflows/combine-json-files.yml
--- a/.github/workflows/combine-json-files.yml
+++ b/.github/workflows/combine-json-files.yml
@@ -38,22 +38,22 @@ jobs:
           echo "Combining sesler from JSON files..."
           mkdir -p kaynak  # "kaynak" klasörünün varlığını garantiye al
       
-          # İlk olarak baska.json dosyasını yeni.json'a yaz
-          jq '{sesler: .sesler}' kaynak/baska.json > kaynak/yeni.json || { echo "Failed to write baska.json"; exit 1; }
+          # İlk olarak baska.json dosyasını fihimafih.json'a yaz
+          jq '{sesler: .sesler}' kaynak/baska.json > kaynak/fihimafih.json || { echo "Failed to write baska.json"; exit 1; }
       
-          # Diğer tüm JSON dosyalarını yeni.json'daki 'sesler' listesine sırayla ekle
+          # Diğer tüm JSON dosyalarını fihimafih.json'daki 'sesler' listesine sırayla ekle
           for file in yunus.json aheng.json cocuk.json cuma.json hakikat.json hu_diyelim.json mevlana.json \
-                      muharrem.json nezih.json niyazi.json nutkuserif.json ramazan.json saz.json tsm.json yeni_mestmp3.json
+                      muharrem.json nezih.json niyazi.json nutkuserif.json ramazan.json saz.json tsm.json fihimafih_mestmp3.json
           do
-            jq '.sesler' "kaynak/$file" | jq -s '.[0] + {sesler: (.[0].sesler + .[1])}' kaynak/yeni.json - > temp.json \
-              && mv temp.json kaynak/yeni.json || { echo "Failed to append $file"; exit 1; }
+            jq '.sesler' "kaynak/$file" | jq -s '.[0] + {sesler: (.[0].sesler + .[1])}' kaynak/fihimafih.json - > temp.json \
+              && mv temp.json kaynak/fihimafih.json || { echo "Failed to append $file"; exit 1; }
           done
 
               # Birleştirilmiş verinin uzunluğunu yazdır
-          echo "The length of the 'sesler' array in yeni.json is:"
-          jq '.sesler | length' kaynak/yeni.json
+          echo "The length of the 'sesler' array in fihimafih.json is:"
+          jq '.sesler | length' kaynak/fihimafih.json
           
-          echo "Successfully combined JSON files into kaynak/yeni.json."
+          echo "Successfully combined JSON files into kaynak/fihimafih.json."
 
 
 
@@ -62,7 +62,7 @@ jobs:
         run: |
           git config --global user.name "GitHub Actions"
           git config --global user.email "actions@github.com"
-          git add kaynak/yeni.json
-          git commit -m "Combine sesler arrays into yeni.json"
+          git add kaynak/fihimafih.json
+          git commit -m "Combine sesler arrays into fihimafih.json"
           git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/benolanben/atesiask.git HEAD:main
 
