Update combine-json-files.yml

diff --git a/.github/workflows/combine-json-files.yml b/.github/workflows/combine-json-files.yml
--- a/.github/workflows/combine-json-files.yml
+++ b/.github/workflows/combine-json-files.yml
@@ -37,15 +37,18 @@ jobs:
           mkdir -p kaynak  # "kaynak" klasörünün varlığını garantiye al
       
           # İlk olarak baska.json dosyasını yeni.json'a yaz
-          jq '. | {sesler: .sesler}' kaynak/baska.json > kaynak/yeni.json || { echo "Failed to write baska.json"; exit 1; }
+          jq '{sesler: .sesler}' kaynak/baska.json > kaynak/yeni.json || { echo "Failed to write baska.json"; exit 1; }
       
-          # Şimdi yunus.json dosyasını yeni.json'a ekle
-          #jq '. | {sesler: .sesler}' kaynak/yunus.json >> kaynak/yeni.json || { echo "Failed to append yunus.json"; exit 1; }
-            # Şimdi yunus.json'daki sesler listesini yeni.json'a ekle
-          jq '.sesler' kaynak/yunus.json | jq -s '.[0] + {sesler: (.[0].sesler + .[1])}' kaynak/yeni.json - > temp.json \
-            && mv temp.json kaynak/yeni.json || { echo "Failed to append yunus.json"; exit 1; }
-          # Birleştirilmiş veriyi kontrol et
+          # Diğer tüm JSON dosyalarını yeni.json'daki 'sesler' listesine sırayla ekle
+          for file in yunus.json aheng.json cocuk.json cuma.json hakikat.json hu_diyelim.json mevlana.json \
+                      muharrem.json nezih.json niyazi.json nutkuserif.json ramazan.json saz.json tsm.json yeni_mestmp3.json
+          do
+            jq '.sesler' "kaynak/$file" | jq -s '.[0] + {sesler: (.[0].sesler + .[1])}' kaynak/yeni.json - > temp.json \
+              && mv temp.json kaynak/yeni.json || { echo "Failed to append $file"; exit 1; }
+          done
+      
           echo "Successfully combined JSON files into kaynak/yeni.json."
+
 
 
 
