Update combine-json-files.yml

diff --git a/.github/workflows/combine-json-files.yml b/.github/workflows/combine-json-files.yml
--- a/.github/workflows/combine-json-files.yml
+++ b/.github/workflows/combine-json-files.yml
@@ -27,15 +27,15 @@ jobs:
         run: |
           echo "Validating baska.json..."
           jq '.' kaynak/baska.json || { echo "Error in baska.json"; exit 1; }
-          echo "Validating saz.json..."
-          jq '.' kaynak/saz.json || { echo "Error in saz.json"; exit 1; }
+          echo "Validating yunus.json..."
+          jq '.' kaynak/yunus.json || { echo "Error in yunus.json"; exit 1; }
 
       # JSON Dosyalarını Birleştir
       - name: Combine "sesler" Arrays
         run: |
           echo "Combining sesler from JSON files..."
           mkdir -p kaynak  # "kaynak" klasörünün varlığını garantiye al
-          jq -s '{sesler: map(.sesler) | add}' kaynak/baska.json > kaynak/yeni.json || { echo "Failed to combine JSON files"; exit 1; }
+          jq -s '{sesler: map(.sesler) | add}' kaynak/baska.json kaynak/yunus.json > kaynak/yeni.json || { echo "Failed to combine JSON files"; exit 1; }
 
       # Değişiklikleri Commit Et ve Pushla
       - name: Commit and push changes
